version: "3"
services:
  student-ai-bot:
    container_name: cwd-bot
    build: ./bot
    depends_on:
      - server
    environment:
      - BOT_TOKEN=5986084810:AAG14PDKkXEjZ64B3utHff7heO4KHL5kaZA
  neftegas-ai-bot:
    container_name: cwd-bot
    build: ./bot
    depends_on:
      - server
    environment:
      - BOT_TOKEN=6359814080:AAFdhF_z8oHpuvyOaHS6I3lgXeo8nsVXB8g
  server:
    container_name: cwd-server
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_TOKEN=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